# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_document}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Balthrop"]
  s.date = %q{2009-11-20}
  s.description = %q{Schemaless models in Berkeley DB.}
  s.email = %q{code@justinbalthrop.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "active_document.gemspec",
     "examples/foo.rb",
     "examples/photo.rb",
     "lib/active_document.rb",
     "lib/active_document/base.rb",
     "test/.gitignore",
     "test/active_document_test.rb",
     "test/deadlock_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/ninjudd/active_document}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Schemaless models in Berkeley DB}
  s.test_files = [
    "test/active_document_test.rb",
     "test/deadlock_test.rb",
     "test/test_helper.rb",
     "examples/foo.rb",
     "examples/photo.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bdb>, [">= 0.1.0"])
      s.add_runtime_dependency(%q<tuple>, [">= 0.1.1"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.0.0"])
    else
      s.add_dependency(%q<bdb>, [">= 0.1.0"])
      s.add_dependency(%q<tuple>, [">= 0.1.1"])
      s.add_dependency(%q<activesupport>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<bdb>, [">= 0.1.0"])
    s.add_dependency(%q<tuple>, [">= 0.1.1"])
    s.add_dependency(%q<activesupport>, [">= 2.0.0"])
  end
end

